version: '2'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: moneyNow
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306

  payment_system:
    build: ./paymentSystem
    environment:
        PHP_IDE_CONFIG: serverName=docker
        XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - ./paymentSystem/www:/var/www/html:cached
      - ./paymentSystem/php.ini:/usr/local/etc/php/php.ini:cached
    depends_on:
      - db
    expose:
      - "9000"
    restart: always

  payment_system_web:
    image: nginx:stable
    volumes:
      - ./paymentSystem/default.conf:/etc/nginx/conf.d/default.conf:cached
    volumes_from:
      - payment_system
    ports:
      - "8080:80"
    links:
      - payment_system
    restart: always
#
#  payment_reciver:
#    build: ./signature_src
#    volumes:
#      - ./signature_src/www:/var/www/html:cached
#      - ./signature_src/php.ini:/usr/local/etc/php/php.ini:cached
#    depends_on:
#      - db
#    expose:
#      - "9000"
#    networks:
#      - default
#    restart: always
#    environment:
#      PHP_IDE_CONFIG: serverName=docker
#      XDEBUG_CONFIG: remote_host=host.docker.internal
#
#  payment_reciver_web:
#    image: nginx:stable
#    volumes:
#      - ./signature_src/default.conf:/etc/nginx/conf.d/default.conf:cached
#    volumes_from:
#      - signature_src
#    ports:
#      - "10001:80"
#    depends_on:
#      - signature_src
#    links:
#      - signature_src
#    restart: always
