version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: moneyNow
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306

  payment_system:
    build: ./paymentSystem
    environment:
        PHP_IDE_CONFIG: serverName=docker
        XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - ./paymentSystem/www:/var/www/html:cached
      - ./paymentSystem/php.ini:/usr/local/etc/php/php.ini:cached
    depends_on:
      - db
    expose:
      - "9000"
    restart: always

  payment_system_web:
    image: nginx:stable
    volumes:
      - ./paymentSystem/default.conf:/etc/nginx/conf.d/default.conf:cached
    volumes_from:
      - payment_system
    ports:
      - "8080:80"
    links:
      - payment_system
    restart: always

# SERVICE 2

  payment_reciver_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: moneyNow
    volumes:
      - ./payment_reciver_db:/var/lib/mysql
    ports:
      - 3308:3306

  payment_reciver:
    build: ./paymentReciver
    environment:
      PHP_IDE_CONFIG: serverName=docker
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - ./paymentReciver/www:/var/www/html:cached
      - ./paymentReciver/php.ini:/usr/local/etc/php/php.ini:cached
    depends_on:
      - payment_reciver_db
    links:
      - payment_system_web
    expose:
      - "9000"
    restart: always

  payment_reciver_web:
    image: nginx:stable
    volumes:
      - ./paymentReciver/default.conf:/etc/nginx/conf.d/default.conf:cached
    volumes_from:
      - payment_reciver
    ports:
      - "8081:80"
    links:
      - payment_reciver
    restart: always
